### ISSUE TITLE
第二种配置

### ISSUE THREAD

**Issue by solo30years** [liang68/ik-analyzer-solr6#2]
您好，尝试过第一种配置后没有问题，第二种配置也在关键位置打日志了，控制台也打了。但是没有输出任何内容

**Comment by solo30years** [comment]
更改后的日志报错，请问如何解决。
java.lang.IllegalStateException: Dictionary词典尚未初始化，请先调用initial方法
	at org.wltea.analyzer.dic.Dictionary.getSingleton(Dictionary.java:103)
	at org.wltea.analyzer.core.CJKSegmenter.analyze(CJKSegmenter.java:80)
	at org.wltea.analyzer.core.IKSegmenter.next(IKSegmenter.java:138)
	at org.wltea.analyzer.lucene.IKTokenizer.incrementToken(IKTokenizer.java:98)
	at org.apache.solr.handler.AnalysisRequestHandlerBase.analyzeTokenStream(AnalysisRequestHandlerBase.java:188)
	at org.apache.solr.handler.AnalysisRequestHandlerBase.analyzeValue(AnalysisRequestHandlerBase.java:127)
	at org.apache.solr.handler.FieldAnalysisRequestHandler.analyzeValues(FieldAnalysisRequestHandler.java:220)
	at org.apache.solr.handler.FieldAnalysisRequestHandler.handleAnalysisRequest(FieldAnalysisRequestHandler.java:181)
	at org.apache.solr.handler.FieldAnalysisRequestHandler.doAnalysis(FieldAnalysisRequestHandler.java:101)
	at org.apache.solr.handler.AnalysisRequestHandlerBase.handleRequestBody(AnalysisRequestHandlerBase.java:72)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:173)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2477)
。。。。。。
